import sys

# print('aaa')
# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13-j_Uazo1OEkGd-fQG_jCm4OysZhpNqv
"""
import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# import nltk
# import re
# from wordcloud import WordCloud

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense, Embedding, LSTM, Conv1D, MaxPool1D
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import classification_report, accuracy_score

import keras
loaded_model = keras.models.load_model('C:\Users\unu\Desktop\SO\modelul_meu_acc_99.hdf5')

loaded_model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['acc'])

loaded_model.summary()

maxlen = 1000

import pickle

with open('C:\Users\unu\Desktop\SO\okenizer.hdf5', 'rb') as handle:
     tokenizer = pickle.load(handle)

x = [' Michael Flynn CRACKS – Will Testify To Mueller Against Trump Himself,"Michael Flynn, Trump s embattled former national security adviser, has reportedly caved in and will testify to Robert Mueller and his team about Trump s collusion with Russia. According to an ABC News special report, Flynn has pleaded guilty to charges that include making false statements to the FBI. Most importantly, he admitted in his plea that officials on Trump s transition team directed his contacts with Russian officials.Furthermore, according to CNN s David Wright on Twitter, there s more to it than that. He s reporting that Brian Ross, who reported for ABC News, said that Flynn also says he s prepared to testify that Trump himself  ordered him, directed him, to make contact with the Russians, which contradicts all that Donald Trump has said at this point. .@BrianRoss reports Michael Flynn  is prepared to testify that President Trump as a candidate   Donald Trump   ordered him, directed him, to make contacts with the Russians, which contradicts all that Donald Trump has said at this point.  David Wright (@DavidWright_CNN) December 1, 2017.@BrianRoss:  As well, we re told that Flynn made the decision to cooperate only in the last 24 hours. That he is distraught about this decision, but feels he is doing the right thing for his country']
# x = tokenizer.texts_to_sequences(x)
# x = pad_sequences(x, maxlen=maxlen)
print(x)
# print(loaded_model.predict(x))



