import sys

# print('aaa')
# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13-j_Uazo1OEkGd-fQG_jCm4OysZhpNqv
"""
import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# import nltk
# import re
# from wordcloud import WordCloud

# from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense, Embedding, LSTM, Conv1D, MaxPool1D
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import classification_report, accuracy_score

import keras
loaded_model = keras.models.load_model('modelul_meu_acc_99.hdf5')

loaded_model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['acc'])

loaded_model.summary()

maxlen = 1000

import pickle

with open('./okenizer.hdf5', 'rb') as handle:
     tokenizer = pickle.load(handle)

x = [' The head of a conservative Republican faction in the U.S. Congress, who voted this month for a huge expansion of the national debt to pay for tax cuts, called himself a “fiscal conservative” on Sunday and urged budget restraint in 2018. In keeping with a sharp pivot under way among Republicans, U.S. Representative Mark Meadows, speaking on CBS’ “Face the Nation,” drew a hard line on federal spending, which lawmakers are bracing to do battle over in January. When they return from the holidays on Wednesday, lawmakers will begin trying to pass a federal budget in a fight likely to be linked to other issues, such as immigration policy, even as the November congressional election campaigns approach in which Republicans will seek to keep control of Congress. President Donald Trump and his Republicans want a big budget increase in military spending, while Democrats also want proportional increases for non-defense “discretionary” spending on programs that support education, scientific research, infrastructure, public health and environmental protection.']
x = tokenizer.texts_to_sequences(x)
x = pad_sequences(x, maxlen=maxlen)
# print(x)
print(loaded_model.predict(x))



